Backend main branch
RISE-drones/drone_interactive_map pull request #27
Opened 2023-04-21 13:38 UTC by Picmick

This branch served as a platform to merge the 3 different branches that were developing the main backend features. These features were the area segmentation and route planning, drone allocation and resource management for auto mode, communication and the control over drone interactions and flight with RDS.

2023-04-24 15:50 UTC, albarv340 requested changes

2023-04-24 15:50 UTC, albarv340 commented on src/back-end/tests/unittests/drone_manager_tests.py
> +from IMM.drone_manager.node import Node
Seemingly unused imports "Route" and "Node"

2023-04-24 15:50 UTC, albarv340 commented on src/back-end/tests/unittests/drone_manager_tests.py
> +        self.r1, self.r2 = generate_dummy_route(offset=0), generate_dummy_route(offset=1)
r1 and r2 could use more descriptive names, e.g. route1 and route2

2023-04-24 15:50 UTC, albarv340 commented on src/back-end/tests/unittests/drone_manager_tests.py
> +class _LinkDummy():
Redundant parenthesis in class definition.
Also, a comment about what this class does, and why its functions seemingly aren't used wouldn't hurt.

2023-04-24 15:50 UTC, albarv340 commented on src/back-end/utility/coordinate_conversion.py
> +def utm_from_latlon(lat, lon):
Are UTM coordinates described anywhere?

2023-04-25 09:37 UTC, alrikmunoz commented on src/back-end/tests/unittests/drone_manager_tests.py
> +        self.r1, self.r2 = generate_dummy_route(offset=0), generate_dummy_route(offset=1)
Not needed here as it is quite obvious that we mean routes, and it would be unnecessarily long to say route1 etc :)

2023-04-26 06:44 UTC, alrikmunoz approved these changes
Beautiful

2023-04-26 06:44 UTC, albarv340 approved these changes

2023-04-26 06:48 UTC, merged